### ISSUE TITLE
라이센스에 대한 명시가 없습니다.

### ISSUE THREAD

**Issue by Darkttd** [ho4040/pini-engine#7]
오픈소스화되면서 이 코드를 사용하는 측에서 이 코드에 대하여 어떤 제약사항을 가지고 어떤 범위까지 사용 가능한지에 대해 명시되어있는 라이센스가 없습니다.

이에 대한 부분 추가 부탁드리겠습니다.

**Comment by Scincy** [comment]
MIT라이센스로 정해졌습니다. 관련 내용으로 추가하면 될 것같습니다.

**Comment by sftblw** [comment]
코드베이스 최상위에 LICENSE / LICENSE.md / COPYING / COPYRIGHT 등의 파일을 생성하여 라이센스를 명시해주시면 좋을 것 같습니다.

부트스트랩 프로젝트 같이 Github에서 LICENSE 파일을 자동으로 인식해서 프로젝트 저장소의 상단에 출력될 수 있었으면 좋겠습니다. [참고: 부트스트랩의 LICENSE 파일 (MIT)](https://github.com/twbs/bootstrap/blob/v4-dev/LICENSE)

**Comment by sftblw** [comment]
이슈가 해결된 것으로 보이면 닫아주시면 감사하겠습니다 `(-_-)` `(_ _)` `(-_-)`
본 이슈는 5e8c2b66f83560e3a6b0b5308df6281bccfb0042 로 해결된 것 같아보입니다.
